# Auto-generated by scripts/run_post_impl_saif.py
set_param general.maxThreads 8
set ::RUN_SAIF_REPO_ROOT {/home/work1/Works/_codex_ai_trigger_saif_20260926c}
set ::RUN_SAIF_DCP {/home/work1/Works/_codex_ai_trigger_saif_20260926c/build/vivado_ooc_ai_trigger/checkpoints/post_route.dcp}
set ::RUN_SAIF_OUT_DIR {/home/work1/Works/_codex_ai_trigger_saif_20260926c/build/vivado_post_impl_saif_30chunks}
set ::RUN_SAIF_REFERENCE {/home/work1/Works/_codex_ai_trigger_saif_20260926c/build/native_validation/reference}
set ::RUN_SAIF_CHUNKS 30
set ::RUN_SAIF_START_WINDOW 96
set ::RUN_SAIF_CNN_THRESH_RAW 0
set ::RUN_SAIF_SDF_MODE none
set ::RUN_SAIF_START_US 0.5
set ::RUN_SAIF_MIN_OBJECTS 1000
cd {/home/work1/Works/_codex_ai_trigger_saif_20260926c}
source {/home/work1/Works/_codex_ai_trigger_saif_20260926c/scripts/vivado_post_impl_saif.tcl}
exit
