set_property SRC_FILE_INFO {cfile:/home/work1/Works/AI-Trigger-System/AI_Trigger_System/AI_Trigger_System.gen/sources_1/ip/fifo_async_1024_to_64/fifo_async_1024_to_64/fifo_async_1024_to_64_in_context.xdc rfile:../../../../../AI_Trigger_System.gen/sources_1/ip/fifo_async_1024_to_64/fifo_async_1024_to_64/fifo_async_1024_to_64_in_context.xdc id:1 order:EARLY scoped_inst:u_HILO_PATH/u_CONNECTOR/u_ASYNC_FIFO} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins u_HILO_PATH/u_CONNECTOR/u_ASYNC_FIFO/rd_clk]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins u_HILO_PATH/u_CONNECTOR/u_ASYNC_FIFO/wr_clk]
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_HILO_PATH/u_CONNECTOR/u_ASYNC_FIFO]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_HILO_PATH/u_CONNECTOR/u_ASYNC_FIFO]
