# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/work1/Works/AI-Trigger-System/AI_Trigger_System/AI_Trigger_System.srcs/sources_1/ip/fifo_async_1024_to_64/fifo_async_1024_to_64.xci
# IP: The module: 'fifo_async_1024_to_64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/work1/Works/AI-Trigger-System/AI_Trigger_System/AI_Trigger_System.gen/sources_1/ip/fifo_async_1024_to_64/fifo_async_1024_to_64.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_async_1024_to_64'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/work1/Works/AI-Trigger-System/AI_Trigger_System/AI_Trigger_System.gen/sources_1/ip/fifo_async_1024_to_64/fifo_async_1024_to_64_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_async_1024_to_64'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/work1/Works/AI-Trigger-System/AI_Trigger_System/AI_Trigger_System.gen/sources_1/ip/fifo_async_1024_to_64/fifo_async_1024_to_64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_async_1024_to_64'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/work1/Works/AI-Trigger-System/AI_Trigger_System/AI_Trigger_System.srcs/sources_1/ip/fifo_async_1024_to_64/fifo_async_1024_to_64.xci
# IP: The module: 'fifo_async_1024_to_64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/work1/Works/AI-Trigger-System/AI_Trigger_System/AI_Trigger_System.gen/sources_1/ip/fifo_async_1024_to_64/fifo_async_1024_to_64.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_async_1024_to_64'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/work1/Works/AI-Trigger-System/AI_Trigger_System/AI_Trigger_System.gen/sources_1/ip/fifo_async_1024_to_64/fifo_async_1024_to_64_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_async_1024_to_64'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/work1/Works/AI-Trigger-System/AI_Trigger_System/AI_Trigger_System.gen/sources_1/ip/fifo_async_1024_to_64/fifo_async_1024_to_64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_async_1024_to_64'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
