# Auto-generated by scripts/run_vivado_build.py
set ::RUN_BUILD_REPO_ROOT {/home/work1/Works/_codex_ai_trigger_native_20260917/system}
set ::RUN_BUILD_OUT_DIR {/home/work1/Works/_codex_ai_trigger_native_20260917/system/../timing-ooc-02}
set ::RUN_BUILD_PART xcku5p-ffvb676-2-e
set ::RUN_BUILD_TOP AI_TRIGGER_TOP
set ::RUN_BUILD_IMPL 1
set ::RUN_BUILD_THREADS 8
set ::RUN_BUILD_MIN_SETUP_SLACK 0.2
cd {/home/work1/Works/_codex_ai_trigger_native_20260917/system}
source {/home/work1/Works/_codex_ai_trigger_native_20260917/system/scripts/vivado_ooc_build.tcl}
exit
