#!/usr/bin/env python3
"""Run AI_TRIGGER_TOP OOC synthesis and implementation from a terminal.

Example:
    python3 scripts/run_vivado_build.py --impl

The flow uses Bender to collect RTL sources, removes dependency board-level
XDC files, applies HDL/constraints/ai_trigger_ooc.xdc, and runs Vivado in
batch mode.  The design is built out of context so the wide DAQ-facing ports
are not implemented as FPGA package IO.
"""

from __future__ import annotations

import argparse
import os
import signal
import shutil
import subprocess
import sys
from pathlib import Path


def tcl_quote(value: str | Path) -> str:
    text = str(value)
    return "{" + text.replace("\\", "\\\\").replace("}", "\\}") + "}"


def find_executable(explicit: str | None, env_name: str, program: str) -> str:
    if explicit:
        return explicit

    env_value = os.environ.get(env_name)
    if env_value:
        return env_value

    found = shutil.which(program)
    if found:
        return found

    raise SystemExit(
        f"ERROR: {program} not found. Add it to PATH or pass --{program} /path/to/{program}."
    )


def build_launcher_tcl(args: argparse.Namespace, repo_root: Path, out_dir: Path) -> str:
    return "\n".join(
        [
            "# Auto-generated by scripts/run_vivado_build.py",
            f"set ::RUN_BUILD_REPO_ROOT {tcl_quote(repo_root)}",
            f"set ::RUN_BUILD_OUT_DIR {tcl_quote(out_dir)}",
            f"set ::RUN_BUILD_PART {args.part}",
            f"set ::RUN_BUILD_TOP {args.top}",
            f"set ::RUN_BUILD_IMPL {1 if args.impl else 0}",
            f"set ::RUN_BUILD_THREADS {args.threads}",
            f"cd {tcl_quote(repo_root)}",
            f"source {tcl_quote(repo_root / 'scripts' / 'vivado_ooc_build.tcl')}",
            "exit",
            "",
        ]
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run AI_TRIGGER_TOP out-of-context Vivado synthesis/implementation."
    )
    parser.add_argument(
        "--vivado",
        help="Vivado executable path. Defaults to $VIVADO or vivado in PATH.",
    )
    parser.add_argument(
        "--bender",
        help="Bender executable path. Defaults to $BENDER or bender in PATH.",
    )
    parser.add_argument(
        "--out-dir",
        default="build/vivado_ooc_ai_trigger",
        help="Output directory for reports, checkpoints, and generated Tcl.",
    )
    parser.add_argument(
        "--part",
        default="xcku5p-ffvb676-2-e",
        help="Target FPGA part.",
    )
    parser.add_argument(
        "--top",
        default="AI_TRIGGER_TOP",
        help="RTL top module/entity for the OOC run.",
    )
    parser.add_argument(
        "--impl",
        action="store_true",
        help="Run opt/place/route after synthesis. Without this, only synthesis runs.",
    )
    parser.add_argument(
        "--threads",
        type=int,
        default=8,
        help="Vivado general.maxThreads value.",
    )
    parser.add_argument(
        "--keep-tcl",
        action="store_true",
        help="Keep the generated launcher Tcl file.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    repo_root = Path(__file__).resolve().parents[1]
    out_dir = Path(args.out_dir).expanduser()
    if not out_dir.is_absolute():
        out_dir = repo_root / out_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    vivado = find_executable(args.vivado, "VIVADO", "vivado")
    bender = find_executable(args.bender, "BENDER", "bender")

    launcher = out_dir / "run_vivado_ooc_build.tcl"
    launcher.write_text(build_launcher_tcl(args, repo_root, out_dir), encoding="utf-8")

    env = os.environ.copy()
    bender_dir = str(Path(bender).resolve().parent)
    env["PATH"] = bender_dir + os.pathsep + env.get("PATH", "")

    cmd = [vivado, "-mode", "batch", "-source", str(launcher)]
    print("INFO: running:", " ".join(cmd), flush=True)
    proc = subprocess.Popen(cmd, cwd=repo_root, env=env)
    try:
        return_code = proc.wait()
    except KeyboardInterrupt:
        print("\nINFO: interrupt received; terminating Vivado...", flush=True)
        proc.send_signal(signal.SIGINT)
        try:
            return_code = proc.wait(timeout=10)
        except subprocess.TimeoutExpired:
            proc.terminate()
            try:
                return_code = proc.wait(timeout=10)
            except subprocess.TimeoutExpired:
                proc.kill()
                return_code = proc.wait()

    if not args.keep_tcl:
        try:
            launcher.unlink()
        except OSError:
            pass

    return return_code


if __name__ == "__main__":
    sys.exit(main())
