#!/usr/bin/env python3
"""Run the Vivado xsim testbench from a plain terminal.

Example:
    python3 scripts/run_vivado_sim.py --num-samples 1000

The script opens AI_Trigger_System/AI_Trigger_System.xpr in Vivado batch mode,
sources run_sim.tcl, and streams Vivado output to the terminal.
"""

from __future__ import annotations

import argparse
import os
import signal
import shutil
import subprocess
import sys
from pathlib import Path


def tcl_quote(value: str | Path) -> str:
    text = str(value)
    return "{" + text.replace("\\", "\\\\").replace("}", "\\}") + "}"


def find_vivado(explicit: str | None) -> str:
    if explicit:
        return explicit

    env_vivado = os.environ.get("VIVADO")
    if env_vivado:
        return env_vivado

    found = shutil.which("vivado")
    if found:
        return found

    raise SystemExit(
        "ERROR: vivado not found. Add Vivado to PATH or pass --vivado /path/to/vivado."
    )


def build_tcl(args: argparse.Namespace, repo_root: Path, project: Path) -> str:
    lines = [
        "# Auto-generated by scripts/run_vivado_sim.py",
        "set_param general.maxThreads 8",
        f"set ::RUN_SIM_REPO_ROOT {tcl_quote(repo_root)}",
    ]

    if args.testhex_dir:
        testhex_dir = Path(args.testhex_dir).expanduser()
        if not testhex_dir.is_absolute():
            testhex_dir = repo_root / testhex_dir
        lines.append(f"set ::RUN_SIM_TESTHEX_DIR {tcl_quote(testhex_dir.resolve())}")
    if args.out_csv:
        lines.append(f"set ::RUN_SIM_OUT_CSV {tcl_quote(args.out_csv)}")
    if args.num_samples is not None:
        lines.append(f"set ::RUN_SIM_NUM_SAMPLES {args.num_samples}")
    if args.score_threshold is not None:
        lines.append(f"set ::RUN_SIM_SCORE_THRESHOLD {args.score_threshold}")
    if args.cnn_thresh_raw is not None:
        lines.append(f"set ::RUN_SIM_CNN_THRESH_RAW {args.cnn_thresh_raw}")

    lines.extend(
        [
            f"cd {tcl_quote(repo_root)}",
            f"open_project {tcl_quote(project)}",
            "update_compile_order -fileset sources_1",
            "update_compile_order -fileset sim_1",
            f"source {tcl_quote(repo_root / 'run_sim.tcl')}",
            "close_project",
            "exit",
            "",
        ]
    )
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run AI_TRIGGER_TOP xsim through Vivado batch mode."
    )
    parser.add_argument(
        "--project",
        default="AI_Trigger_System/AI_Trigger_System.xpr",
        help="Vivado project path, relative to repo root by default.",
    )
    parser.add_argument(
        "--vivado",
        help="Vivado executable path. Defaults to $VIVADO or vivado in PATH.",
    )
    parser.add_argument(
        "--num-samples",
        type=int,
        help="Pass +NUM_SAMPLES=<N> to tb_ai_trigger_top.sv.",
    )
    parser.add_argument(
        "--testhex-dir",
        help="Pass +TESTHEX_DIR=<path>. Defaults to the symlink created by run_sim.tcl.",
    )
    parser.add_argument(
        "--out-csv",
        help="Pass +OUT_CSV=<path>. Defaults to ai_trigger_results.csv in xsim dir.",
    )
    parser.add_argument(
        "--score-threshold",
        type=float,
        help="Pass +SCORE_THRESHOLD=<f> to the testbench checker. Default is -6.0 in the testbench.",
    )
    parser.add_argument(
        "--cnn-thresh-raw",
        type=int,
        help="Pass +CNN_THRESH_RAW=<N> to the DUT threshold input. Default is -12288 in the testbench.",
    )
    parser.add_argument(
        "--keep-tcl",
        action="store_true",
        help="Keep the generated Tcl file under .sim_batch/.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    repo_root = Path(__file__).resolve().parents[1]
    project = Path(args.project).expanduser()
    if not project.is_absolute():
        project = repo_root / project
    project = project.resolve()

    if not project.exists():
        raise SystemExit(f"ERROR: Vivado project not found: {project}")

    vivado = find_vivado(args.vivado)
    work_dir = repo_root / ".sim_batch"
    work_dir.mkdir(exist_ok=True)
    tcl_path = work_dir / "run_vivado_sim_batch.tcl"
    tcl_path.write_text(build_tcl(args, repo_root, project), encoding="utf-8")

    cmd = [vivado, "-mode", "batch", "-source", str(tcl_path)]
    print("INFO: running:", " ".join(cmd), flush=True)
    proc = subprocess.Popen(cmd, cwd=repo_root)
    try:
        return_code = proc.wait()
    except KeyboardInterrupt:
        print("\nINFO: interrupt received; terminating Vivado...", flush=True)
        proc.send_signal(signal.SIGINT)
        try:
            return_code = proc.wait(timeout=10)
        except subprocess.TimeoutExpired:
            proc.terminate()
            try:
                return_code = proc.wait(timeout=10)
            except subprocess.TimeoutExpired:
                proc.kill()
                return_code = proc.wait()

    if not args.keep_tcl:
        try:
            tcl_path.unlink()
        except OSError:
            pass

    return return_code


if __name__ == "__main__":
    sys.exit(main())
