#!/usr/bin/env python3
"""Run routed gate-level xsim to generate SAIF and a power report.

Default flow:
    python3 scripts/run_post_impl_saif.py

The script first builds an OOC routed checkpoint with the flat-port simulation
wrapper as top, then runs the existing testbench against the routed netlist,
writes SAIF activity, and feeds that SAIF into Vivado report_power.
"""

from __future__ import annotations

import argparse
import os
import signal
import shutil
import subprocess
import sys
from pathlib import Path


def tcl_quote(value: str | Path) -> str:
    text = str(value)
    return "{" + text.replace("\\", "\\\\").replace("}", "\\}") + "}"


def find_executable(explicit: str | None, env_name: str, program: str) -> str:
    if explicit:
        return explicit

    env_value = os.environ.get(env_name)
    if env_value:
        return env_value

    found = shutil.which(program)
    if found:
        return found

    raise SystemExit(
        f"ERROR: {program} not found. Add it to PATH or pass --{program} /path/to/{program}."
    )


def run_process(cmd: list[str], cwd: Path, env: dict[str, str]) -> int:
    print("INFO: running:", " ".join(cmd), flush=True)
    proc = subprocess.Popen(cmd, cwd=cwd, env=env)
    try:
        return proc.wait()
    except KeyboardInterrupt:
        print("\nINFO: interrupt received; terminating Vivado...", flush=True)
        proc.send_signal(signal.SIGINT)
        try:
            return proc.wait(timeout=10)
        except subprocess.TimeoutExpired:
            proc.terminate()
            try:
                return proc.wait(timeout=10)
            except subprocess.TimeoutExpired:
                proc.kill()
                return proc.wait()


def build_ooc_launcher(args: argparse.Namespace, repo_root: Path, build_dir: Path) -> str:
    return "\n".join(
        [
            "# Auto-generated by scripts/run_post_impl_saif.py",
            f"set ::RUN_BUILD_REPO_ROOT {tcl_quote(repo_root)}",
            f"set ::RUN_BUILD_OUT_DIR {tcl_quote(build_dir)}",
            f"set ::RUN_BUILD_PART {args.part}",
            "set ::RUN_BUILD_TOP AI_TRIGGER_TOP_TB_WRAP",
            "set ::RUN_BUILD_IMPL 1",
            f"set ::RUN_BUILD_THREADS {args.threads}",
            f"cd {tcl_quote(repo_root)}",
            f"source {tcl_quote(repo_root / 'scripts' / 'vivado_ooc_build.tcl')}",
            "exit",
            "",
        ]
    )


def build_saif_launcher(
    args: argparse.Namespace,
    repo_root: Path,
    dcp: Path,
    out_dir: Path,
) -> str:
    lines = [
        "# Auto-generated by scripts/run_post_impl_saif.py",
        f"set_param general.maxThreads {args.threads}",
        f"set ::RUN_SAIF_REPO_ROOT {tcl_quote(repo_root)}",
        f"set ::RUN_SAIF_DCP {tcl_quote(dcp)}",
        f"set ::RUN_SAIF_OUT_DIR {tcl_quote(out_dir)}",
        f"set ::RUN_SAIF_NUM_SAMPLES {args.samples}",
        f"set ::RUN_SAIF_SCORE_THRESHOLD {args.score_threshold}",
        f"set ::RUN_SAIF_CNN_THRESH_RAW {args.cnn_thresh_raw}",
        f"set ::RUN_SAIF_SDF_MODE {args.sdf}",
        f"set ::RUN_SAIF_START_US {args.saif_start_us}",
        f"set ::RUN_SAIF_SCOPE {args.saif_scope}",
        f"set ::RUN_SAIF_MIN_OBJECTS {args.saif_min_objects}",
        f"set ::RUN_SAIF_FALLBACK_ALL {0 if args.no_saif_fallback_all else 1}",
    ]
    if args.testhex_dir:
        testhex_dir = Path(args.testhex_dir).expanduser()
        if not testhex_dir.is_absolute():
            testhex_dir = repo_root / testhex_dir
        lines.append(f"set ::RUN_SAIF_TESTHEX_DIR {tcl_quote(testhex_dir.resolve())}")
    lines.extend(
        [
            f"cd {tcl_quote(repo_root)}",
            f"source {tcl_quote(repo_root / 'scripts' / 'vivado_post_impl_saif.tcl')}",
            "exit",
            "",
        ]
    )
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate post-implementation SAIF activity and a Vivado power report."
    )
    parser.add_argument(
        "--vivado",
        help="Vivado executable path. Defaults to $VIVADO or vivado in PATH.",
    )
    parser.add_argument(
        "--bender",
        help="Bender executable path. Defaults to $BENDER or bender in PATH.",
    )
    parser.add_argument(
        "--build-dir",
        default="build/vivado_ooc_ai_trigger_wrap",
        help="OOC implementation directory for the flat-port wrapper checkpoint.",
    )
    parser.add_argument(
        "--out-dir",
        default="build/vivado_post_impl_saif",
        help="Output directory for netlist, xsim files, SAIF, and reports.",
    )
    parser.add_argument(
        "--dcp",
        help="Use an existing routed checkpoint instead of the default wrapper checkpoint.",
    )
    parser.add_argument(
        "--skip-build",
        action="store_true",
        help="Do not build the wrapper checkpoint before running gate simulation.",
    )
    parser.add_argument(
        "--samples",
        type=int,
        default=16,
        help="Number of samples to run in gate-level simulation. Default: 16.",
    )
    parser.add_argument(
        "--sdf",
        choices=["none", "min", "typ", "max"],
        default="none",
        help="SDF annotation mode. Use none for faster SAIF; max for a short timing smoke test.",
    )
    parser.add_argument(
        "--saif-start-us",
        type=float,
        default=2.0,
        help="Delay before SAIF recording starts, in microseconds. Default: 2.0.",
    )
    parser.add_argument(
        "--saif-scope",
        choices=["top", "lane0", "lanes2", "lanes4", "all"],
        default="all",
        help="SAIF logging scope. Default logs top, distributor, and all seven lanes in separate chunks.",
    )
    parser.add_argument(
        "--saif-min-objects",
        type=int,
        default=1000,
        help="Fail if SAIF logging matches fewer objects than this. Default: 1000.",
    )
    parser.add_argument(
        "--no-saif-fallback-all",
        action="store_true",
        help="Disable raw full-DUT recursive SAIF fallback when scoped logging matches too few objects.",
    )
    parser.add_argument(
        "--testhex-dir",
        help="Directory containing testhex_stream files. Defaults to the Bender checkout.",
    )
    parser.add_argument(
        "--score-threshold",
        type=float,
        default=-6.0,
        help="Classification threshold for the testbench checker.",
    )
    parser.add_argument(
        "--cnn-thresh-raw",
        type=int,
        default=-96,
        help="Raw signed CNN_THRESH value driven into the DUT.",
    )
    parser.add_argument(
        "--part",
        default="xcku5p-ffvb676-2-e",
        help="Target FPGA part used when building the wrapper checkpoint.",
    )
    parser.add_argument(
        "--threads",
        type=int,
        default=8,
        help="Vivado general.maxThreads value.",
    )
    parser.add_argument(
        "--keep-tcl",
        action="store_true",
        help="Keep generated launcher Tcl files.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    repo_root = Path(__file__).resolve().parents[1]

    build_dir = Path(args.build_dir).expanduser()
    if not build_dir.is_absolute():
        build_dir = repo_root / build_dir
    build_dir.mkdir(parents=True, exist_ok=True)

    out_dir = Path(args.out_dir).expanduser()
    if not out_dir.is_absolute():
        out_dir = repo_root / out_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    if args.dcp:
        dcp = Path(args.dcp).expanduser()
        if not dcp.is_absolute():
            dcp = repo_root / dcp
    else:
        dcp = build_dir / "checkpoints" / "post_route.dcp"

    vivado = find_executable(args.vivado, "VIVADO", "vivado")
    env = os.environ.copy()
    vivado_dir = str(Path(vivado).resolve().parent)
    env["PATH"] = vivado_dir + os.pathsep + env.get("PATH", "")

    if not args.skip_build:
        bender = find_executable(args.bender, "BENDER", "bender")
        bender_dir = str(Path(bender).resolve().parent)
        env["PATH"] = bender_dir + os.pathsep + env.get("PATH", "")

        build_gen_dir = build_dir / "generated"
        build_gen_dir.mkdir(parents=True, exist_ok=True)
        build_tcl = build_gen_dir / "run_vivado_ooc_wrapper_build.tcl"
        build_tcl.write_text(build_ooc_launcher(args, repo_root, build_dir), encoding="utf-8")
        ret = run_process([vivado, "-mode", "batch", "-source", str(build_tcl)], repo_root, env)
        if ret != 0:
            return ret
        if not args.keep_tcl:
            try:
                build_tcl.unlink()
            except OSError:
                pass

    if not dcp.exists():
        raise SystemExit(f"ERROR: routed checkpoint not found: {dcp}")

    saif_gen_dir = out_dir / "generated"
    saif_gen_dir.mkdir(parents=True, exist_ok=True)
    saif_tcl = saif_gen_dir / "run_vivado_post_impl_saif.tcl"
    saif_tcl.write_text(build_saif_launcher(args, repo_root, dcp, out_dir), encoding="utf-8")
    ret = run_process([vivado, "-mode", "batch", "-source", str(saif_tcl)], repo_root, env)
    if not args.keep_tcl:
        try:
            saif_tcl.unlink()
        except OSError:
            pass
    return ret


if __name__ == "__main__":
    sys.exit(main())
