#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Jul 06 18:58:03 PDT 2026
# SW Build 4029153 on Fri Oct 13 20:13:54 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_AI_TRIGGER_TOP_behav -key {Behavioral:sim_1:Functional:tb_AI_TRIGGER_TOP} -tclbatch tb_AI_TRIGGER_TOP.tcl -log simulate.log -testplusarg OUT_CSV=ai_trigger_results.csv -testplusarg EVENT_CSV=ai_trigger_events.csv -testplusarg NUM_SAMPLES=1000 -testplusarg SCORE_THRESHOLD=0.0 -testplusarg CNN_THRESH_RAW=0"
xsim tb_AI_TRIGGER_TOP_behav -key {Behavioral:sim_1:Functional:tb_AI_TRIGGER_TOP} -tclbatch tb_AI_TRIGGER_TOP.tcl -log simulate.log -testplusarg OUT_CSV=ai_trigger_results.csv -testplusarg EVENT_CSV=ai_trigger_events.csv -testplusarg NUM_SAMPLES=1000 -testplusarg SCORE_THRESHOLD=0.0 -testplusarg CNN_THRESH_RAW=0

