#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Jul 26 15:49:08 PDT 2026
# SW Build 4029153 on Fri Oct 13 20:13:54 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_AI_TRIGGER_TOP_behav -key {Behavioral:sim_1:Functional:tb_AI_TRIGGER_TOP} -tclbatch tb_AI_TRIGGER_TOP.tcl -log simulate.log -testplusarg TESTHEX_DIR=/home/work1/Works/AI-Trigger-System/build/bringup_sim/monopolar_10mv_10ns_erf_tr10ns_sweep/testhex_stream -testplusarg OUT_CSV=/home/work1/Works/AI-Trigger-System/build/bringup_sim/monopolar_10mv_10ns_erf_tr10ns_sweep/scores.csv -testplusarg EVENT_CSV=/home/work1/Works/AI-Trigger-System/build/bringup_sim/monopolar_10mv_10ns_erf_tr10ns_sweep/events.csv -testplusarg NUM_SAMPLES=266 -testplusarg SCORE_THRESHOLD=0.0 -testplusarg CNN_THRESH_RAW=0 -testplusarg MIRROR_RAW_CHANNELS=0"
xsim tb_AI_TRIGGER_TOP_behav -key {Behavioral:sim_1:Functional:tb_AI_TRIGGER_TOP} -tclbatch tb_AI_TRIGGER_TOP.tcl -log simulate.log -testplusarg TESTHEX_DIR=/home/work1/Works/AI-Trigger-System/build/bringup_sim/monopolar_10mv_10ns_erf_tr10ns_sweep/testhex_stream -testplusarg OUT_CSV=/home/work1/Works/AI-Trigger-System/build/bringup_sim/monopolar_10mv_10ns_erf_tr10ns_sweep/scores.csv -testplusarg EVENT_CSV=/home/work1/Works/AI-Trigger-System/build/bringup_sim/monopolar_10mv_10ns_erf_tr10ns_sweep/events.csv -testplusarg NUM_SAMPLES=266 -testplusarg SCORE_THRESHOLD=0.0 -testplusarg CNN_THRESH_RAW=0 -testplusarg MIRROR_RAW_CHANNELS=0

